### ISSUE TITLE
Сохранения не работают.

### ISSUE THREAD

**Issue by Grokon** [sanscriptum/jack#4]
Последний фикс - перестали работать сохранения.

П.С. Так же хочу заметить, что теперь текст стал сливаться с фоном, а то его и вовсе перестало быть видно.

**Comment by evpevp** [comment]
Сохранения прошлой версии не должны работать в новой. Это ожидаемое поведение.
Для корректного отображения оформления нужна новая версия FastQSP.

**Comment by Grokon** [comment]
Наверное не совсем верно выразился. Проблема не в том что они не грузятся, а в том что они вообще не создаются. Т.е. нажимаю "Сохранить" название  - ентер, далее смотрю в папке, куда должно было сохраниться - файл отсутствует. Так же ранее был файл autosav (насколько я понял это что-то вроде автосохранения), но он так же не создается.

**Comment by sanscriptum** [comment]
Сними атрибут "только для чтения" с папки. Чтобы элементы отображались, нужно убрать все пробелы в пути к игре, это баг плеера.

**Comment by Grokon** [comment]
Как выяснилось - проблема наблюдалась из-за локали, стояла японская, после изменения на русскую - сохранения заработали. Скорее всего - действительно это проблема плеера и нужно отписывать в багтреккер плеера, только вот до обновления с яп локалью все работало.

Так что проблему можно считать решенной и можно закрыть. Единственное - прошу учесть момент, который я описал в первом сообщении в "пс"

**Comment by evpevp** [comment]
На твой ПС был дан ответ выше: "Чтобы элементы отображались, нужно убрать все пробелы в пути к игре, это баг плеера."
